### ISSUE TITLE
Fuel\Core\FuelException [ Error ]:

### ISSUE THREAD

**Issue by Link0Darck** [nenuadrian/hacker-rpg-php-browser-based-game#107]
Hello,
I did exactly what you said but it doesn't work
Sincerely

`Error!
Fuel\Core\FuelException [ Error ]:
There is no security.output_filter defined in your application config file

COREPATH/classes/security.php @ line 75
70        }
71
72        // throw an exception if the output filter setting is missing from the app config
73        if (\Config::get('security.output_filter', null) === null)
74        {
75            throw new \FuelException('There is no security.output_filter defined in your application config file');
76        }
77
78        // deal with duplicate filters, no need to slow the framework down
79        foreach (array('output_filter', 'uri_filter', 'input_filter') as $setting)
80        {
Backtrace
COREPATH/classes/autoloader.php @ line 377
372            if (static::$auto_initialize === $class)
373            {
374                static::$auto_initialize = null;
375                if (method_exists($class, '_init') and is_callable($class.'::_init'))
376                {
377                    call_user_func($class.'::_init');
378                }
379            }
380        }
381
382        // or an interface...
COREPATH/classes/autoloader.php @ line 249
244            }
245            if ( ! class_exists($class, false))
246            {
247                class_alias($full_class, $class);
248            }
249            static::init_class($class);
250            $loaded = true;
251        }
252        else
253        {
254            $full_ns = substr($class, 0, $pos);
COREPATH/base.php @ line 258
253 */
254if ( ! function_exists('e'))
255{
256    function e($string)
257    {
258        return \Security::htmlentities($string);
259    }
260}
261
262/**
263 * Takes a classname and returns the actual classname for an alias or just the classname
COREPATH/views/errors/php_fatal_error.php @ line 37
32</head>
33<body>
34    <div id="wrapper">
35        <h1><?php echo $severity; ?>!</h1>
36
37        <p class="intro"><?php echo $type; ?> [ echo $severity; ?> ]:<br />echo e($message); ?></p>
38
39        <h2 class="first"><?php echo $filepath; ?> @ line echo $error_line; ?></h2>
40
41<?php if (is_array($debug_lines)): ?>
42<pre class="fuel_debug_source"><?php foreach ($debug_lines as $line_num => $line_content): ?>
COREPATH/classes/view.php @ line 244
239            ob_start();
240
241            try
242            {
243                // Load the view within the current scope
244                include $__file_name;
245            }
246            catch (\Exception $e)
247            {
248                // Delete the output buffer
249                ob_end_clean();
COREPATH/classes/view.php @ line 260
255            // Get the captured output and close the buffer
256            return ob_get_clean();
257        };
258
259        // import and process the view file
260        $result = $clean_room($file_override ?: $this->file_name, $data = $this->get_data());
261
262        // disable sanitization on objects that support it
263        $this->unsanitize($data);
264
265        // return the result
COREPATH/classes/view.php @ line 665
660        {
661            throw new \FuelException('You must set the file to use within your view before rendering');
662        }
663
664        // combine local and global data and capture the output
665        $return = $this->process_file();
666
667        // restore the current language setting
668        $this->active_language and \Config::set('language', $current_language);
669
670        // and the active request class
COREPATH/classes/view.php @ line 213
208     */
209    public function __toString()
210    {
211        try
212        {
213            return $this->render();
214        }
215        catch (\Exception $e)
216        {
217            \Errorhandler::exception_handler($e);
218
COREPATH/classes/errorhandler.php @ line 252
247
248            $data['non_fatal'] = static::$non_fatal_cache;
249
250            try
251            {
252                exit(\View::forge('errors'.DS.'php_fatal_error', $data, false));
253            }
254            catch (\FuelException $view_exception)
255            {
256                exit($data['severity'].' - '.$data['message'].' in '.\Fuel::clean_path($data['filepath']).' on line '.$data['error_line']);
257            }
COREPATH/classes/errorhandler.php @ line 130
125            $severity = ( ! isset(static::$levels[$e->getCode()])) ? $e->getCode() : static::$levels[$e->getCode()];
126            logger(static::$loglevel, $severity.' - '.$e->getMessage().' in '.$e->getFile().' on line '.$e->getLine());
127
128            if (\Fuel::$env != \Fuel::PRODUCTION)
129            {
130                static::show_php_error($e);
131            }
132            else
133            {
134                static::show_production_error($e);
135            }
COREPATH/bootstrap.php @ line 87
82        include COREPATH.'classes/errorhandler.php';
83        class_alias('\Fuel\Core\Errorhandler', 'Errorhandler');
84        class_alias('\Fuel\Core\PhpErrorException', 'PhpErrorException');
85    }
86
87    return \Errorhandler::exception_handler($e);
88});
89
90set_error_handler(function ($severity, $message, $filepath, $line)
91{
92    // reset the autoloader
FuelPHP is released under the MIT license.`

**Comment by nenuadrian** [comment]
There were a few updates last month, could you try from scratch and let me know if still the same issue? There is a setup system avaialble now as well to create the table structure if you manually create the database (readme has been updated)

I have seen your error before - but if you're going to face it with a fresh install, will provide direct guidance

**Comment by nenuadrian** [comment]
Perhaps try 

//'output_filter'  => array('Security::htmlentities'),
		'output_filter' => array(),

Not commenting output_filter

Please re-open if still issue / if you want to try again
