### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MexasPT** [nenuadrian/hacker-rpg-php-browser-based-game#110]
Can you help me?

[almix@cpanel118 game]$ composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - overtrue/phplint is locked to version 3.0.3 and an update of this package was not requested.
    - overtrue/phplint 3.0.3 requires php >=8.0 -> your php version (7.3.33) does not satisfy that requirement.
  Problem 2
    - psr/container is locked to version 1.1.2 and an update of this package was not requested.
    - psr/container 1.1.2 requires php >=7.4.0 -> your php version (7.3.33) does not satisfy that requirement.
  Problem 3
    - psr/container 1.1.2 requires php >=7.4.0 -> your php version (7.3.33) does not satisfy that requirement.
    - symfony/service-contracts v2.4.0 requires psr/container ^1.1 -> satisfiable by psr/container[1.1.2].
    - symfony/service-contracts is locked to version v2.4.0 and an update of this package was not requested.

**Comment by nenuadrian** [comment]
Hello

Per the errors PHP >=8.0 would be required 

Would you be able to try that?

**Comment by MexasPT** [comment]
With PHP 8 and 8.1
And the error says that the php version is 7.4.28 but it is incorrect.
The php is already in version 8.0.

`Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - overtrue/phplint is locked to version 3.0.3 and an update of this package was not requested.
    - overtrue/phplint 3.0.3 requires php >=8.0 -> your php version (7.4.28) does not satisfy that requirement.
    - `
![php81](https://user-images.githubusercontent.com/17734465/162979545-d1e21078-1156-4484-9265-303d8e06467e.png)

**Comment by nenuadrian** [comment]
I believe none of those packages may be needed anyway especially         "overtrue/phplint": "^3.0"

It's just to have some tools for code checking

Open new if you can't run it even with these errors
